/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiPublicHlsRouteImport } from './routes/api/public/hls'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHlsRoute = ApiPublicHlsRouteImport.update({
  id: '/api/public/hls',
  path: '/api/public/hls',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/hls': typeof ApiPublicHlsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/hls': typeof ApiPublicHlsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/hls': typeof ApiPublicHlsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/watch/$id' | '/api/public/hls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/watch/$id' | '/api/public/hls'
  id: '__root__' | '/' | '/watch/$id' | '/api/public/hls'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchIdRoute: typeof WatchIdRoute
  ApiPublicHlsRoute: typeof ApiPublicHlsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hls': {
      id: '/api/public/hls'
      path: '/api/public/hls'
      fullPath: '/api/public/hls'
      preLoaderRoute: typeof ApiPublicHlsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchIdRoute: WatchIdRoute,
  ApiPublicHlsRoute: ApiPublicHlsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
